### ISSUE TITLE
AssertionError: Invalid format of declaration.

### ISSUE THREAD

**Issue by BlackLacost** [zxqfox/step-by-step-1#1]
Возник один вопрос, если обновить gulp-bem-bundler-fs с 0.0.4 до 0.0.6 версии. При сборке появилась ошибка:
```
AssertionError: Invalid format of declaration.
    at parse (D:\...\...\frontend\node_modules\gulp-bem-bundler-fs\node_modules\bem-decl\lib\parse.js:37:13)
```
Как правильно теперь писать декларацию?

**Comment by skad0** [comment]
Продублирую [отсюда](https://github.com/gulp-bem/gulp-bem-bundler-fs/pull/9):
В данный момент нужно писать, например, так:
```javascript
({
    decl: [
      'page',
      'link',
      'col',
      'heading',
      'header',
      'logo',
      'nav',
      'content'
    ]
})
```

Документации, к сожалению, еще нет, но примеры посмотреть можно [тут](https://github.com/bem-sdk/bem-decl/tree/master/test/parse)
